version: '3.8'

services:
  next:
    build:
      context: .
      dockerfile: apps/next/Dockerfile
    volumes:
      - ./apps/next:/app/apps/next
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
    network_mode: host

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./packages/api:/app/packages/api
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rumourcast
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: